#!/bin/bash
# This script builds the Rusty entropyx WASM32 SDK release.

# make the script fail for any failed command
set -e

rm -rf release/*
rm -rf web/*
rm -rf nodejs/*
rm -rf docs/*
rm -rf examples/nodejs/typescript/lib

mkdir -p release/entropyx-wasm32-sdk/web
mkdir -p release/entropyx-wasm32-sdk/nodejs
mkdir -p release/entropyx-wasm32-sdk/docs

# pushd .
# cd ../rpc/wrpc/wasm
# wasm-pack build --target web --out-name entropyx-rpc --out-dir web/entropyx-rpc --features wasm32-sdk $@
# popd

wasm-pack build --weak-refs --target web --out-name entropyx --out-dir web/entropyx-keygen --features wasm32-keygen $@
wasm-pack build --weak-refs --dev --target web --out-name entropyx --out-dir web/entropyx-keygen-dev --features wasm32-keygen $@

wasm-pack build --weak-refs --target web --out-name entropyx --out-dir web/entropyx-rpc --features wasm32-rpc $@
wasm-pack build --weak-refs --dev --target web --out-name entropyx --out-dir web/entropyx-rpc-dev --features wasm32-rpc $@

wasm-pack build --weak-refs --target web --out-name entropyx --out-dir web/entropyx-core --features wasm32-core $@
wasm-pack build --weak-refs --dev --target web --out-name entropyx --out-dir web/entropyx-core-dev --features wasm32-core $@

wasm-pack build --weak-refs --target web --out-name entropyx --out-dir web/entropyx --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target web --out-name entropyx --out-dir web/entropyx-dev --features wasm32-sdk $@

wasm-pack build --weak-refs --target nodejs --out-name entropyx --out-dir nodejs/entropyx --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target nodejs --out-name entropyx --out-dir nodejs/entropyx-dev --features wasm32-sdk $@

# wasm-pack build --target web --dev --out-name entropyx --out-dir build/docs/entropyx --features wasm32-sdk $@
typedoc --name "entropyx WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/entropyx-keygen ./build/docs/entropyx-keygen.ts
typedoc --name "entropyx WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/entropyx-rpc ./build/docs/entropyx-rpc.ts
typedoc --name "entropyx WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/entropyx-core ./build/docs/entropyx-core.ts
typedoc --name "entropyx WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/entropyx ./build/docs/entropyx.ts

# cp -r ../rpc/wrpc/wasm/web/entropyx-rpc release/entropyx-wasm32-sdk/web/entropyx-rpc
cp -r web/entropyx-keygen release/entropyx-wasm32-sdk/web/entropyx-keygen
cp -r web/entropyx-keygen-dev release/entropyx-wasm32-sdk/web/entropyx-keygen-dev

cp -r web/entropyx-rpc release/entropyx-wasm32-sdk/web/entropyx-rpc
cp -r web/entropyx-rpc-dev release/entropyx-wasm32-sdk/web/entropyx-rpc-dev

cp -r web/entropyx-core release/entropyx-wasm32-sdk/web/entropyx-core
cp -r web/entropyx-core-dev release/entropyx-wasm32-sdk/web/entropyx-core-dev

cp -r web/entropyx release/entropyx-wasm32-sdk/web/entropyx
cp -r web/entropyx-dev release/entropyx-wasm32-sdk/web/entropyx-dev

cp -r nodejs/entropyx release/entropyx-wasm32-sdk/nodejs/entropyx
cp -r nodejs/entropyx-dev release/entropyx-wasm32-sdk/nodejs/entropyx-dev

cp -r docs/entropyx-keygen release/entropyx-wasm32-sdk/docs/entropyx-keygen
cp -r docs/entropyx-rpc release/entropyx-wasm32-sdk/docs/entropyx-rpc
cp -r docs/entropyx-core release/entropyx-wasm32-sdk/docs/entropyx-core
cp -r docs/entropyx release/entropyx-wasm32-sdk/docs/entropyx

mkdir -p release/entropyx-wasm32-sdk/examples/data
cp -r examples/data/.gitignore release/entropyx-wasm32-sdk/examples/data/.gitignore
cp -r examples/nodejs release/entropyx-wasm32-sdk/examples/
cp -r examples/web release/entropyx-wasm32-sdk/examples/
cp -r examples/init.js release/entropyx-wasm32-sdk/examples/
cp -r examples/jsconfig.json release/entropyx-wasm32-sdk/examples/
cp -r examples/package.json release/entropyx-wasm32-sdk/examples/

pushd .
cd release/entropyx-wasm32-sdk/examples
npm install
popd

# tsc release/entropyx-wasm32-sdk/examples/nodejs/typescript/

cp index.html release/entropyx-wasm32-sdk/index.html
cp README.md release/entropyx-wasm32-sdk/README.md
cp CHANGELOG.md release/entropyx-wasm32-sdk/CHANGELOG.md
cp LICENSE release/entropyx-wasm32-sdk/LICENSE

node build/package-sizes.js
cp package-sizes.js release/entropyx-wasm32-sdk/package-sizes.js

pushd .
cd release
zip -q -r entropyx-wasm32-sdk.zip entropyx-wasm32-sdk
popd
