[package]
name = "entropyx-wrpc-example-subscriber"
description = "EntropyX wRPC subscription example"
publish = false
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
futures.workspace = true
entropyx-consensus-core.workspace = true
entropyx-rpc-core.workspace = true
entropyx-wrpc-client.workspace = true
entropyx-notify.workspace = true
tokio.workspace = true
workflow-core.workspace = true
workflow-log.workspace = true
ctrlc.workspace = true
